import { ContextProvider } from "../components/client";

export const metadata = {
  title: "Pagination App",
  description: "Generated by Next.js",
};
import "../styles/globals.css";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
